// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpxwupykirsrazbrvdxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpweHd1cHlraXJzcmF6YnJ2ZHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTEzMDEsImV4cCI6MjA1OTc2NzMwMX0.ym3UguhCR6KDvUL0JcE5Sk5NXkUWjfYSpg7AAHlYYhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);